# This job is the main jobs will dispatch build and test for every modules of our mono repo.
name: Lint

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  linelint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Linelint
        uses: fernandrone/linelint@0.0.4
        id: linelint

      - name: actionlint
        uses: raven-actions/actionlint@01fce4f43a270a612932cb1c64d40505a029f821 # v2.0.0

      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@0901cf7b71c7ea6261ec69a3dc2bd3f9264f893e # v3.0.12
